apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: kubernetes.docker.internal  # furanocoumarins.belozersky.msu.ru
    http:
      paths:
      - path: /api/search-alpha/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: search-alpha
            port:
              number: 80
      - path: /api/admin/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin-all
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
