
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['go-auth:80']

  - job_name: 'prometheus-runtime'
    static_configs:
      - targets: ['go-auth:5000']
  