apiVersion: apps/v1
kind: Deployment
metadata:
 name: admin-all
 labels:
   app: admin-all
spec:
 replicas: 1
 selector:
   matchLabels:
     app: admin-all
 template:
   metadata:
     labels:
       app: admin-all
   spec:
     containers:
     - name: admin-all
       image: olegkaps/chem-admin:1.1
       ports:
       - containerPort: 8080
       imagePullPolicy: IfNotPresent
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: admin-all
spec:
  type: ClusterIP
  selector:
    app: admin-all
  ports:
  - port: 80
    targetPort: 8080